export enum CorrelationType {
  COMORBIDITY = 'COMORBIDITY',
  RISK_FACTOR = 'RISK_FACTOR',
  CARE_CONTEXT = 'CARE_CONTEXT',
  LIFESTYLE_LINK = 'LIFESTYLE_LINK',
  PREVENTIVE_LINK = 'PREVENTIVE_LINK',
}
