export enum QuizLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}

export enum QuizTheme {
  PREVENTION = 'PREVENTION',
  FOLLOW_UP = 'FOLLOW_UP',
  TREATMENT = 'TREATMENT',
  COMPLICATIONS = 'COMPLICATIONS',
  LIFESTYLE = 'LIFESTYLE',
  NUTRITION = 'NUTRITION',
  ADHERENCE = 'ADHERENCE',
  RISK_FACTORS = 'RISK_FACTORS',
}

export enum QuizQuestionType {
  SINGLE_CHOICE = 'SINGLE_CHOICE',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  BOOLEAN = 'BOOLEAN',
}

export enum QuizStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum QuizAttemptStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}
